--- #YAML:1.0
name:                Lingua-Translit
version:             0.15
abstract:            transliterates text between writing systems
license:             ~
author:              
    - Alex Linke <alinke@lingua-systems.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
